-- =========================================================
-- TABELA: CLIENTE
-- =========================================================

CREATE TABLE cliente (
id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
nome VARCHAR2(200) NOT NULL,
cpf VARCHAR2(11) NOT NULL,
email VARCHAR2(150),
telefone VARCHAR2(20),
data_cadastro DATE NOT NULL,

CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),

CONSTRAINT uq_cliente_cpf UNIQUE (cpf)
);


-- =========================================================
-- TABELA: FORNECEDOR
-- =========================================================

CREATE TABLE fornecedor (
id_fornecedor NUMBER GENERATED BY DEFAULT AS IDENTITY,
nome VARCHAR2(200) NOT NULL,
cnpj VARCHAR2(14) NOT NULL,
email VARCHAR2(150),
telefone VARCHAR2(20),

CONSTRAINT pk_fornecedor PRIMARY KEY (id_fornecedor),

CONSTRAINT uq_fornecedor_cnpj UNIQUE (cnpj)
);


-- =========================================================
-- TABELA: FUNCIONARIO
-- =========================================================

CREATE TABLE funcionario (
id_funcionario NUMBER GENERATED BY DEFAULT AS IDENTITY,
nome VARCHAR2(200) NOT NULL,
cpf VARCHAR2(11) NOT NULL,
cargo VARCHAR2(100) NOT NULL,
salario NUMBER(10,2) NOT NULL,
data_contratacao DATE NOT NULL,

CONSTRAINT pk_funcionario PRIMARY KEY (id_funcionario),

CONSTRAINT uq_funcionario_cpf UNIQUE (cpf),

CONSTRAINT ck_funcionario_salario CHECK (salario > 0)
);


-- =========================================================
-- TABELA: PRODUTO
-- =========================================================

CREATE TABLE produto (
id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY,
nome VARCHAR2(200) NOT NULL,
descricao VARCHAR2(500),
preco NUMBER(10,2) NOT NULL,
quantidade_estoque NUMBER NOT NULL,
id_fornecedor NUMBER NOT NULL,

CONSTRAINT pk_produto PRIMARY KEY (id_produto),

CONSTRAINT ck_produto_preco CHECK (preco > 0),
CONSTRAINT ck_produto_estoque CHECK (quantidade_estoque >= 0),

CONSTRAINT fk_produto_fornecedorFOREIGN KEY (id_fornecedor)REFERENCES fornecedor(id_fornecedor)
);


-- =========================================================
-- TABELA: PEDIDO
-- =========================================================

CREATE TABLE pedido (
id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY,
data_pedido DATE NOT NULL,
status VARCHAR2(30) NOT NULL,
valor_total NUMBER(10,2) NOT NULL,
id_funcionario NUMBER NOT NULL,
id_cliente NUMBER NOT NULL,

CONSTRAINT pk_pedido PRIMARY KEY (id_pedido),

CONSTRAINT ck_pedido_valor CHECK (valor_total >= 0),

CONSTRAINT fk_pedido_funcionarioFOREIGN KEY (id_funcionario) REFERENCES funcionario(id_funcionario),
CONSTRAINT fk_pedido_clienteFOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);


-- =========================================================
-- TABELA: ITEM_PEDIDO
-- =========================================================

CREATE TABLE item_pedido (
id_item NUMBER GENERATED BY DEFAULT AS IDENTITY,
quantidade NUMBER NOT NULL,
preco_unitario NUMBER(10,2) NOT NULL,
id_pedido NUMBER NOT NULL,
id_produto NUMBER NOT NULL,

CONSTRAINT pk_item_pedido PRIMARY KEY (id_item),

CONSTRAINT ck_item_quantidade CHECK (quantidade > 0),
CONSTRAINT ck_item_preco CHECK (preco_unitario > 0),

CONSTRAINT fk_item_pedidoFOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
CONSTRAINT fk_item_produtoFOREIGN KEY (id_produto) REFERENCES produto(id_produto)
);


-- =========================================================
-- TABELA: PAGAMENTO
-- =========================================================

CREATE TABLE pagamento (
id_pagamento NUMBER GENERATED BY DEFAULT AS IDENTITY,
tipo_pagamento VARCHAR2(30) NOT NULL,
valor NUMBER(10,2) NOT NULL,
data_pagamento DATE NOT NULL,
status VARCHAR2(30) NOT NULL,
id_pedido NUMBER NOT NULL,

CONSTRAINT pk_pagamento PRIMARY KEY (id_pagamento),

CONSTRAINT ck_pagamento_valor CHECK (valor > 0),

CONSTRAINT uq_pagamento_pedido UNIQUE (id_pedido)

CONSTRAINT fk_pagamento_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
);